POST http://192.168.1.110:9999/tessar/statis/statis
Accept:*/*
Cache-Control:no-cache
Content-Type:application.json

{"uid":10023722086,"regdate":1514184954,"lastdate":1514184954,"channel_from":"ngBrazil","gid":"bloodstrke","sub":"lp-fb","sid":"0"}

###

POST http://192.168.1.110:9999/tessar/statis/statis
Accept:*/*
Cache-Control:no-cache

{"uid":10023722086,"regdate":1514184954,"lastdate":1514184954,"channel_from":"ngBrazil","gid":"bloodstrke","sub":"lp-fb","sid":"0"}

###

POST http://192.168.1.110:9999/tessar/statis/statis
Accept:*/*
Cache-Control:no-cache

{"uid":10023722086,"regdate":1514184954,"lastdate":1514184954,"channel_from":"ngBrazil","gid":"bloodstrke","sub":"lp-fb","sid":"0"}

###

POST http://192.168.1.110:9999/tessar/statis/statis?=
Accept:*/*
Cache-Control:no-cache

{"uid":10023722086,"regdate":1514184954,"lastdate":1514184954,"channel_from":"ngBrazil","gid":"bloodstrke","sub":"lp-fb","sid":"0"}

###

GET http://192.168.1.110:9999/tessar/statis/statis?aa=22&name=[s,c,d]
Accept:*/*
Cache-Control:no-cache

###

GET http://192.168.1.110:9999/tessar/statis/statis?aa=22&name=[s,c,d]
Accept:*/*
Cache-Control:no-cache

###

GET 127.0.0.1:9999/tessar/statis/statis?aa=22&name=[s,c,d]
Accept:*/*
Cache-Control:no-cache

###

GET http://127.0.0.1:9999/tessar/statis/statis?aa=22&name=[s,c,d]
Accept:*/*
Cache-Control:no-cache

###

GET http://127.0.0.1:9999/tessar/statis/statis?aa=22&name=vova
Accept:*/*
Cache-Control:no-cache

###

GET http://127.0.0.1:9999/tessar/statis/statis?aa=22&name=vova
Accept:*/*
Cache-Control:no-cache

###

GET http://127.0.0.1:9999/tessar/statis/statis?aa=22&name=vova
Accept:*/*
Cache-Control:no-cache

###

GET http://127.0.0.1:9999/tessar/statis/statis?aa=22&name=vova
Accept:*/*
Cache-Control:no-cache

###

GET http://127.0.0.1:9999/tessar/statis/statis
Accept:*/*
Cache-Control:no-cache

###

GET http://127.0.0.1:9999/tessar/statis/statis?aa=22&name=vova
Accept:*/*
Cache-Control:no-cache

###

GET http://127.0.0.1:9999/tessar/statis/statis?aa=22
Accept:*/*
Cache-Control:no-cache

###

GET http://127.0.0.1:9999/tessar/statis/statis?aa=22&name=vova
Accept:*/*
Cache-Control:no-cache

###

GET http://127.0.0.1:9999/tessar/statis/statis?aa=22&name=vova
Accept:*/*
Cache-Control:no-cache

###

GET http://127.0.0.1:9999/tessar/statis/statis?aa=22&name=vova
Accept:*/*
Cache-Control:no-cache

###

GET http://localhost:9999/tessar/statis/statis%20
Accept:*/*
Cache-Control:no-cache

###

GET http://localhost:8080/tessar/statis/statis%20
Accept:*/*
Cache-Control:no-cache

###

GET http://localhost:8080/tessar/statis/statis
Accept:*/*
Cache-Control:no-cache

###

